name: Run PHP CS Fixer

on:
  push:
    branches: [ 'main', 'develop', 'feature/**', 'release/**' ]
    paths: ['src/**.php']

jobs:
  php-cs-fixer:
    name: Run PHP CS Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run PHP CS Fixer
        uses: luminsports/github-action-php-cs-fixer@main
